//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De32.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class HoaDonBan
    { 
        [Key]
        public int MaHD { get; set; }
        [ForeignKey("Sach")]
        public int MaSach { get; set; }
        [ForeignKey("KhachHang")]
        public int MaKH { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}")]
        public System.DateTime NgayBan { get; set; }
        [Range(1,int.MaxValue)]
        public int SoLuong { get; set; }
        public decimal DonGia => Sach?.DonGia ?? 0;
        public decimal ThanhTien => SoLuong * DonGia;
        public virtual KhachHang KhachHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
