//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De32.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.HoaDonBans = new HashSet<HoaDonBan>();
        }
        [Key]
        public int MaSach { get; set; }
        [Required]
        [StringLength(50,MinimumLength =5)]
        public string TenSach { get; set; }
        [Required]
        public string TheLoai { get; set; }
        [Required]
        [Range(1, int.MaxValue)]
        public decimal DonGia { get; set; }
        [Required]
        [Range(0, int.MaxValue)]
        public int SoLuongTon { get; set; }
        // Kiểm tra thể loại có chiều dài tối đa 30 ký tự
        public bool KTTheLoai()
        {
            if (this.TheLoai.Length > 30) return false;
            return true;
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
    }
}
